// Code generated by colgen v0.1.2; DO NOT EDIT.
package tradeplus

import "tradebot/pkg/db"

type Cards []Card

func (ll Cards) IndexByNmID() map[int]Card {
	r := make(map[int]Card, len(ll))
	for i := range ll {
		r[ll[i].NmID] = ll[i]
	}
	return r
}

type Reviews []Review

func (ll Reviews) IDs() []int {
	r := make([]int, len(ll))
	for i := range ll {
		r[i] = ll[i].ID
	}
	return r
}

func (ll Reviews) Index() map[int]Review {
	r := make(map[int]Review, len(ll))
	for i := range ll {
		r[ll[i].ID] = ll[i]
	}
	return r
}

func NewReviews(in []db.Review) Reviews { return MapP(in, NewReview) }

func (ll Reviews) UniqueExternalIDs() []string {
	idx := make(map[string]struct{}, len(ll))
	for i := range ll {
		if _, ok := idx[ll[i].ExternalID]; !ok {
			idx[ll[i].ExternalID] = struct{}{}
		}
	}

	r, i := make([]string, len(idx)), 0
	for k := range idx {
		r[i] = k
		i++
	}
	return r
}

func (ll Reviews) IndexByExternalID() map[string]Review {
	r := make(map[string]Review, len(ll))
	for i := range ll {
		r[ll[i].ExternalID] = ll[i]
	}
	return r
}
