// Code generated by mfd-generator v0.6.0; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (c Cabinet) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(c.Name) > 64 {
		errors[Columns.Cabinet.Name] = ErrMaxLength
	}

	if c.ClientID != nil && utf8.RuneCountInString(*c.ClientID) > 64 {
		errors[Columns.Cabinet.ClientID] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Key) > 1024 {
		errors[Columns.Cabinet.Key] = ErrMaxLength
	}

	if c.SheetLink != nil && utf8.RuneCountInString(*c.SheetLink) > 1024 {
		errors[Columns.Cabinet.SheetLink] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (o Order) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(o.PostingNumber) > 32 {
		errors[Columns.Order.PostingNumber] = ErrMaxLength
	}

	if utf8.RuneCountInString(o.Article) > 128 {
		errors[Columns.Order.Article] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (s Stock) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(s.Article) > 64 {
		errors[Columns.Stock.Article] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (u User) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if u.CabinetIDs == nil {
		errors[Columns.User.CabinetIDs] = ErrEmptyValue
	}

	if u.Login != nil && utf8.RuneCountInString(*u.Login) > 64 {
		errors[Columns.User.Login] = ErrMaxLength
	}

	if u.Password != nil && utf8.RuneCountInString(*u.Password) > 64 {
		errors[Columns.User.Password] = ErrMaxLength
	}

	if u.AuthKey != nil && utf8.RuneCountInString(*u.AuthKey) > 32 {
		errors[Columns.User.AuthKey] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (r Review) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(r.ExternalID) > 128 {
		errors[Columns.Review.ExternalID] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.Article) > 128 {
		errors[Columns.Review.Article] = ErrMaxLength
	}

	if utf8.RuneCountInString(r.CustomerName) > 32 {
		errors[Columns.Review.CustomerName] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
