// Code generated by mfd-generator v0.6.1; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"encoding/json"
	"time"
)

var Columns = struct {
	Cabinet struct {
		ID, Name, ClientID, Key, Marketplace, Type, SheetLink, StatusID, Settings string
	}
	Order struct {
		ID, PostingNumber, Article, Count, CabinetID, CreatedAt, StatusID string

		Cabinet string
	}
	Stock struct {
		ID, Article, UpdatedAt, CountFbo, CountFbs, CabinetID string

		Cabinet string
	}
	User struct {
		ID, TgID, IsAdmin, CabinetIDs, StatusID, Login, Password, AuthKey, CreatedAt, LastActivityAt string
	}
	Review struct {
		ID, CabinetID, ExternalID, Text, Pros, Cons, Valuation, Answer, Article, CreatedAt, StatusID, CustomerName, Photos, ToOperator string

		Cabinet string
	}
	Product struct {
		ID, CabinetID, Article, Title, ExternalID, Description, RecommendationIDs, StatusID string

		Cabinet string
	}
	VfsFile struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}
	VfsFolder struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}
	VfsHash struct {
		Hash, Namespace, Extension, FileSize, Width, Height, Blurhash, Error, CreatedAt, IndexedAt string
	}
}{
	Cabinet: struct {
		ID, Name, ClientID, Key, Marketplace, Type, SheetLink, StatusID, Settings string
	}{
		ID:          "cabinetId",
		Name:        "name",
		ClientID:    "clientId",
		Key:         "key",
		Marketplace: "marketplace",
		Type:        "type",
		SheetLink:   "sheetLink",
		StatusID:    "statusId",
		Settings:    "settings",
	},
	Order: struct {
		ID, PostingNumber, Article, Count, CabinetID, CreatedAt, StatusID string

		Cabinet string
	}{
		ID:            "orderId",
		PostingNumber: "postingNumber",
		Article:       "article",
		Count:         "count",
		CabinetID:     "cabinetId",
		CreatedAt:     "createdAt",
		StatusID:      "statusId",

		Cabinet: "Cabinet",
	},
	Stock: struct {
		ID, Article, UpdatedAt, CountFbo, CountFbs, CabinetID string

		Cabinet string
	}{
		ID:        "stockId",
		Article:   "article",
		UpdatedAt: "updatedAt",
		CountFbo:  "countFbo",
		CountFbs:  "countFbs",
		CabinetID: "cabinetId",

		Cabinet: "Cabinet",
	},
	User: struct {
		ID, TgID, IsAdmin, CabinetIDs, StatusID, Login, Password, AuthKey, CreatedAt, LastActivityAt string
	}{
		ID:             "userId",
		TgID:           "tgId",
		IsAdmin:        "isAdmin",
		CabinetIDs:     "cabinetIds",
		StatusID:       "statusId",
		Login:          "login",
		Password:       "password",
		AuthKey:        "authKey",
		CreatedAt:      "createdAt",
		LastActivityAt: "lastActivityAt",
	},
	Review: struct {
		ID, CabinetID, ExternalID, Text, Pros, Cons, Valuation, Answer, Article, CreatedAt, StatusID, CustomerName, Photos, ToOperator string

		Cabinet string
	}{
		ID:           "reviewId",
		CabinetID:    "cabinetId",
		ExternalID:   "externalId",
		Text:         "text",
		Pros:         "pros",
		Cons:         "cons",
		Valuation:    "valuation",
		Answer:       "answer",
		Article:      "article",
		CreatedAt:    "createdAt",
		StatusID:     "statusId",
		CustomerName: "customerName",
		Photos:       "photos",
		ToOperator:   "toOperator",

		Cabinet: "Cabinet",
	},
	Product: struct {
		ID, CabinetID, Article, Title, ExternalID, Description, RecommendationIDs, StatusID string

		Cabinet string
	}{
		ID:                "productId",
		CabinetID:         "cabinetId",
		Article:           "article",
		Title:             "title",
		ExternalID:        "externalId",
		Description:       "description",
		RecommendationIDs: "recommendationIds",
		StatusID:          "statusId",

		Cabinet: "Cabinet",
	},
	VfsFile: struct {
		ID, FolderID, Title, Path, Params, IsFavorite, MimeType, FileSize, FileExists, CreatedAt, StatusID string

		Folder string
	}{
		ID:         "fileId",
		FolderID:   "folderId",
		Title:      "title",
		Path:       "path",
		Params:     "params",
		IsFavorite: "isFavorite",
		MimeType:   "mimeType",
		FileSize:   "fileSize",
		FileExists: "fileExists",
		CreatedAt:  "createdAt",
		StatusID:   "statusId",

		Folder: "Folder",
	},
	VfsFolder: struct {
		ID, ParentFolderID, Title, IsFavorite, CreatedAt, StatusID string

		ParentFolder string
	}{
		ID:             "folderId",
		ParentFolderID: "parentFolderId",
		Title:          "title",
		IsFavorite:     "isFavorite",
		CreatedAt:      "createdAt",
		StatusID:       "statusId",

		ParentFolder: "ParentFolder",
	},
	VfsHash: struct {
		Hash, Namespace, Extension, FileSize, Width, Height, Blurhash, Error, CreatedAt, IndexedAt string
	}{
		Hash:      "hash",
		Namespace: "namespace",
		Extension: "extension",
		FileSize:  "fileSize",
		Width:     "width",
		Height:    "height",
		Blurhash:  "blurhash",
		Error:     "error",
		CreatedAt: "createdAt",
		IndexedAt: "indexedAt",
	},
}

var Tables = struct {
	Cabinet struct {
		Name, Alias string
	}
	Order struct {
		Name, Alias string
	}
	Stock struct {
		Name, Alias string
	}
	User struct {
		Name, Alias string
	}
	Review struct {
		Name, Alias string
	}
	Product struct {
		Name, Alias string
	}
	VfsFile struct {
		Name, Alias string
	}
	VfsFolder struct {
		Name, Alias string
	}
	VfsHash struct {
		Name, Alias string
	}
}{
	Cabinet: struct {
		Name, Alias string
	}{
		Name:  "cabinets",
		Alias: "t",
	},
	Order: struct {
		Name, Alias string
	}{
		Name:  "orders",
		Alias: "t",
	},
	Stock: struct {
		Name, Alias string
	}{
		Name:  "stocks",
		Alias: "t",
	},
	User: struct {
		Name, Alias string
	}{
		Name:  "users",
		Alias: "t",
	},
	Review: struct {
		Name, Alias string
	}{
		Name:  "reviews",
		Alias: "t",
	},
	Product: struct {
		Name, Alias string
	}{
		Name:  "products",
		Alias: "t",
	},
	VfsFile: struct {
		Name, Alias string
	}{
		Name:  "vfsFiles",
		Alias: "t",
	},
	VfsFolder: struct {
		Name, Alias string
	}{
		Name:  "vfsFolders",
		Alias: "t",
	},
	VfsHash: struct {
		Name, Alias string
	}{
		Name:  "vfsHashes",
		Alias: "t",
	},
}

type Cabinet struct {
	tableName struct{} `pg:"cabinets,alias:t,discard_unknown_columns"`

	ID          int             `pg:"cabinetId,pk"`
	Name        string          `pg:"name,use_zero"`
	ClientID    *string         `pg:"clientId"`
	Key         string          `pg:"key,use_zero"`
	Marketplace string          `pg:"marketplace,use_zero"`
	Type        string          `pg:"type,use_zero"`
	SheetLink   *string         `pg:"sheetLink"`
	StatusID    int             `pg:"statusId,use_zero"`
	Settings    CabinetSettings `pg:"settings,use_zero"`
}

type Order struct {
	tableName struct{} `pg:"orders,alias:t,discard_unknown_columns"`

	ID            int       `pg:"orderId,pk"`
	PostingNumber string    `pg:"postingNumber,use_zero"`
	Article       string    `pg:"article,use_zero"`
	Count         int       `pg:"count,use_zero"`
	CabinetID     int       `pg:"cabinetId,use_zero"`
	CreatedAt     time.Time `pg:"createdAt,use_zero"`
	StatusID      int       `pg:"statusId,use_zero"`

	Cabinet *Cabinet `pg:"fk:cabinetId,rel:has-one"`
}

type Stock struct {
	tableName struct{} `pg:"stocks,alias:t,discard_unknown_columns"`

	ID        int       `pg:"stockId,pk"`
	Article   string    `pg:"article,use_zero"`
	UpdatedAt time.Time `pg:"updatedAt,use_zero"`
	CountFbo  *int      `pg:"countFbo"`
	CountFbs  *int      `pg:"countFbs"`
	CabinetID int       `pg:"cabinetId,use_zero"`

	Cabinet *Cabinet `pg:"fk:cabinetId,rel:has-one"`
}

type User struct {
	tableName struct{} `pg:"users,alias:t,discard_unknown_columns"`

	ID             int        `pg:"userId,pk"`
	TgID           int64      `pg:"tgId,use_zero"`
	IsAdmin        bool       `pg:"isAdmin,use_zero"`
	CabinetIDs     []int      `pg:"cabinetIds,array"`
	StatusID       int        `pg:"statusId,use_zero"`
	Login          *string    `pg:"login"`
	Password       *string    `pg:"password"`
	AuthKey        *string    `pg:"authKey"`
	CreatedAt      time.Time  `pg:"createdAt,use_zero"`
	LastActivityAt *time.Time `pg:"lastActivityAt"`
}

type Review struct {
	tableName struct{} `pg:"reviews,alias:t,discard_unknown_columns"`

	ID         int       `pg:"reviewId,pk"`
	CabinetID  int       `pg:"cabinetId,use_zero"`
	ExternalID string    `pg:"externalId,use_zero"`
	Valuation  int       `pg:"valuation,use_zero"`
	Answer     string    `pg:"answer,use_zero"`
	Article    string    `pg:"article,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`
	ToOperator bool      `pg:"toOperator,use_zero"`
	// Payload holds the full review content and WB-derived context as jsonb
	// (text/pros/cons/customerName/photos + enrichment). See tradeplus.ReviewPayload.
	// Replaces the former text/pros/cons/customerName/photos columns.
	Payload json.RawMessage `pg:"payload,type:jsonb"`

	Cabinet *Cabinet `pg:"fk:cabinetId,rel:has-one"`
}

type Product struct {
	tableName struct{} `pg:"products,alias:t,discard_unknown_columns"`

	ID                int     `pg:"productId,pk"`
	CabinetID         int     `pg:"cabinetId,use_zero"`
	Article           string  `pg:"article,use_zero"`
	Title             string  `pg:"title,use_zero"`
	ExternalID        string  `pg:"externalId,use_zero"`
	Description       *string `pg:"description"`
	RecommendationIDs []int   `pg:"recommendationIds,array"`
	StatusID          int     `pg:"statusId,use_zero"`

	Cabinet *Cabinet `pg:"fk:cabinetId,rel:has-one"`
}

type VfsFile struct {
	tableName struct{} `pg:"vfsFiles,alias:t,discard_unknown_columns"`

	ID         int       `pg:"fileId,pk"`
	FolderID   int       `pg:"folderId,use_zero"`
	Title      string    `pg:"title,use_zero"`
	Path       string    `pg:"path,use_zero"`
	Params     *string   `pg:"params"`
	IsFavorite *bool     `pg:"isFavorite"`
	MimeType   string    `pg:"mimeType,use_zero"`
	FileSize   *int      `pg:"fileSize"`
	FileExists bool      `pg:"fileExists,use_zero"`
	CreatedAt  time.Time `pg:"createdAt,use_zero"`
	StatusID   int       `pg:"statusId,use_zero"`

	Folder *VfsFolder `pg:"fk:folderId,rel:has-one"`
}

type VfsFolder struct {
	tableName struct{} `pg:"vfsFolders,alias:t,discard_unknown_columns"`

	ID             int       `pg:"folderId,pk"`
	ParentFolderID *int      `pg:"parentFolderId"`
	Title          string    `pg:"title,use_zero"`
	IsFavorite     *bool     `pg:"isFavorite"`
	CreatedAt      time.Time `pg:"createdAt,use_zero"`
	StatusID       int       `pg:"statusId,use_zero"`

	ParentFolder *VfsFolder `pg:"fk:parentFolderId,rel:has-one"`
}

type VfsHash struct {
	tableName struct{} `pg:"vfsHashes,alias:t,discard_unknown_columns"`

	Hash      string     `pg:"hash,pk"`
	Namespace string     `pg:"namespace,pk"`
	Extension string     `pg:"extension,use_zero"`
	FileSize  int        `pg:"fileSize,use_zero"`
	Width     int        `pg:"width,use_zero"`
	Height    int        `pg:"height,use_zero"`
	Blurhash  *string    `pg:"blurhash"`
	Error     *string    `pg:"error"`
	CreatedAt time.Time  `pg:"createdAt,use_zero"`
	IndexedAt *time.Time `pg:"indexedAt"`
}
