alter table public.cabinets
    rename column "cabinetsId" to "cabinetId";

create table reviews
(
    "reviewId"     integer generated by default as identity
        primary key,
    "cabinetId"    integer                                not null
        constraint "Ref_reviews_to_cabinets"
            references cabinets,
    "externalId"   varchar(128)                           not null,
    "customerName" varchar(32)                            not null,
    text           text                                   not null,
    pros           text                                   not null,
    cons           text                                   not null,
    valuation      integer                                not null,
    answer         text                                   not null,
    article        varchar(128)                           not null,
    "createdAt"    timestamp with time zone default now() not null,
    "statusId"     integer                                not null
        constraint "Ref_reviews_to_statuses"
            references statuses
);

