create table products
(
    "productId"         integer generated by default as identity
        primary key,
    "cabinetId"         integer      not null
        constraint "Ref_products_to_cabinets"
            references cabinets,
    article             varchar(128) not null,
    title               varchar(128) not null,
    "externalId"        varchar(128) not null,
    description         text,
    "recommendationIds" integer[],
    "statusId"          integer      not null
        constraint "Ref_products_to_statuses"
            references statuses
);

create index "articleIdx"
    on products (article);

