// Code generated by colgen v0.1.2; DO NOT EDIT.
package wb

type Cards []Card

func (ll Cards) IndexByNmID() map[int]Card {
	r := make(map[int]Card, len(ll))
	for i := range ll {
		r[ll[i].NmID] = ll[i]
	}
	return r
}
