CREATE TYPE "marketplaces" AS ENUM ('WB', 'OZON', 'YANDEX');

CREATE TYPE "types" AS ENUM ('fbo', 'fbs', 'all');

CREATE TABLE "cabinets" (
	"cabinetId" SERIAL NOT NULL,
	"name" varchar(64) NOT NULL,
	"clientId" varchar(64),
	"key" varchar(1024) NOT NULL,
	"marketplace" marketplaces NOT NULL,
	"type" types NOT NULL,
	"sheetLink" varchar(1024),
	"settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
	"statusId" integer NOT NULL,
	CONSTRAINT "cabinets_pkey" PRIMARY KEY("cabinetId")
);

CREATE TABLE "orders" (
	"orderId" SERIAL NOT NULL,
	"postingNumber" varchar(32) NOT NULL,
	"article" varchar(128) NOT NULL,
	"count" integer NOT NULL,
	"cabinetId" integer NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "orders_pkey" PRIMARY KEY("orderId")
);

CREATE TABLE "products" (
	"productId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cabinetId" integer NOT NULL,
	"article" varchar(128) NOT NULL,
	"title" varchar(128) NOT NULL,
	"externalId" varchar(128) NOT NULL,
	"description" text,
	"recommendationIds" integer[],
	"statusId" integer NOT NULL,
	CONSTRAINT "products_pkey" PRIMARY KEY("productId")
);

CREATE TABLE "reviews" (
	"reviewId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"cabinetId" integer NOT NULL,
	"externalId" varchar(128) NOT NULL,
	"customerName" varchar(32) NOT NULL DEFAULT '',
	"text" text NOT NULL,
	"pros" text NOT NULL,
	"cons" text NOT NULL,
	"valuation" integer NOT NULL,
	"answer" text NOT NULL,
	"article" varchar(128) NOT NULL,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "reviews_pkey" PRIMARY KEY("reviewId")
);

CREATE TABLE "statuses" (
	"statusId" SERIAL NOT NULL,
	"title" varchar(255) NOT NULL,
	"alias" varchar(64) NOT NULL,
	CONSTRAINT "statuses_pkey" PRIMARY KEY("statusId")
);

CREATE TABLE "stocks" (
	"stockId" SERIAL NOT NULL,
	"article" varchar(64) NOT NULL,
	"updatedAt" timestamptz NOT NULL DEFAULT now(),
	"countFbo" integer,
	"countFbs" integer,
	"cabinetId" integer NOT NULL,
	CONSTRAINT "stocks_pkey" PRIMARY KEY("stockId")
);

CREATE TABLE "users" (
	"userId" SERIAL NOT NULL,
	"tgId" bigint NOT NULL,
	"login" varchar(64),
	"password" varchar(64),
	"authKey" varchar(32),
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"lastActivityAt" timestamptz,
	"isAdmin" boolean NOT NULL DEFAULT false,
	"cabinetIds" integer[],
	"statusId" integer NOT NULL,
	CONSTRAINT "users_pkey" PRIMARY KEY("userId")
);

CREATE TABLE "vfsFiles" (
	"fileId" SERIAL NOT NULL,
	"folderId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"path" varchar(255) NOT NULL,
	"params" text,
	"isFavorite" boolean DEFAULT false,
	"mimeType" varchar(255) NOT NULL,
	"fileSize" integer DEFAULT 0,
	"fileExists" boolean NOT NULL DEFAULT true,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "vfsFiles_pkey" PRIMARY KEY("fileId")
);

CREATE TABLE "vfsFolders" (
	"folderId" SERIAL NOT NULL,
	"parentFolderId" integer,
	"title" varchar(255) NOT NULL,
	"isFavorite" boolean DEFAULT false,
	"createdAt" timestamp NOT NULL DEFAULT now(),
	"statusId" integer NOT NULL,
	CONSTRAINT "vfsFolders_pkey" PRIMARY KEY("folderId")
);

CREATE TABLE "vfsHashes" (
	"hash" varchar(40) NOT NULL,
	"namespace" varchar(32) NOT NULL,
	"extension" varchar(4) NOT NULL,
	"fileSize" integer NOT NULL DEFAULT 0,
	"width" integer NOT NULL DEFAULT 0,
	"height" integer NOT NULL DEFAULT 0,
	"blurhash" text,
	"error" text,
	"createdAt" timestamptz NOT NULL DEFAULT now(),
	"indexedAt" timestamptz,
	CONSTRAINT "vfsHashes_pkey" PRIMARY KEY("hash", "namespace")
);

CREATE INDEX "IX_FK_orders_cabinetId_orders" ON "orders" (
	"cabinetId"
);

CREATE INDEX "IX_FK_products_cabinetId_products" ON "products" (
	"cabinetId"
);

CREATE INDEX "IX_FK_users_statusId_users" ON "users" (
	"statusId"
);

CREATE INDEX "IX_FK_vfsFiles_folderId_vfsFiles" ON "vfsFiles" (
	"folderId"
);

CREATE INDEX "IX_FK_vfsFiles_statusId_vfsFiles" ON "vfsFiles" (
	"statusId"
);

CREATE INDEX "IX_FK_vfsFolders_folderId_vfsFolders" ON "vfsFolders" (
	"parentFolderId"
);

CREATE INDEX "IX_FK_vfsFolders_statusId_vfsFolders" ON "vfsFolders" (
	"statusId"
);

CREATE INDEX "IX_reviews_externalId" ON "reviews" (
	"externalId"
);

CREATE UNIQUE INDEX "IX_tgId_unique" ON "users" (
	"tgId"
);

CREATE INDEX "IX_vfsHashes_indexedAt" ON "vfsHashes" (
	"indexedAt"
);

CREATE INDEX "articleIdx" ON "products" (
	"article"
);

ALTER TABLE "cabinets" ADD CONSTRAINT "Ref_cabinets_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "orders" ADD CONSTRAINT "Ref_orders_to_cabinets" FOREIGN KEY ("cabinetId")
	REFERENCES "cabinets"("cabinetId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "orders" ADD CONSTRAINT "Ref_orders_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "products" ADD CONSTRAINT "Ref_products_to_cabinets" FOREIGN KEY ("cabinetId")
	REFERENCES "cabinets"("cabinetId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "products" ADD CONSTRAINT "Ref_products_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_cabinets" FOREIGN KEY ("cabinetId")
	REFERENCES "cabinets"("cabinetId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "reviews" ADD CONSTRAINT "Ref_reviews_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "stocks" ADD CONSTRAINT "Ref_stocks_to_cabinets" FOREIGN KEY ("cabinetId")
	REFERENCES "cabinets"("cabinetId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "users" ADD CONSTRAINT "Ref_users_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "Ref_vfsFiles_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "vfsFiles" ADD CONSTRAINT "Ref_vfsFiles_to_vfsFolders" FOREIGN KEY ("folderId")
	REFERENCES "vfsFolders"("folderId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "Ref_vfsFolders_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "vfsFolders" ADD CONSTRAINT "Ref_vfsFolders_to_vfsFolders" FOREIGN KEY ("parentFolderId")
	REFERENCES "vfsFolders"("folderId")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

